### ISSUE TITLE
Arch issues/packages

### ISSUE THREAD

**Issue by icebal** [cawilliamson/ansible-gpdpocket#73]
When you submit an Issue report - please provide the following information:

- [ ] Brief description of the issue you are seeing.
- [ ] All command output from any commands you were running (can be pulled using `pastebinit`.)
- [ ] What you have tried so far.

So far I have noticed some irregularities with bootstrapping an arch install.

1. No battery icon, even with the latest pull. Trying to get battery info from acpi, /sys/class/yadda/yadda doesn't show anything for percentages or charge. Closest is charging and discharging. Is there a specific package needed to be installed?

2. Bootup pauses for 1m30s waiting for -.device. no mention of this on the interwebs, and no issue with this on a regular install.

3. Brcmfmac is not set on bootup. This is easy to fix manually, but would be great in the ansible playbook.

4. Touchscreen only acts as left mouse click. This I dont know if its a arch specific issue, or general linux issue. Touchegg looks like it would be a good fit in this case.

5. Dkms modules. Since your renaming the initrd and everything, this is breaking dkms and anything that needs headers. if you keep the kernel and such the original name, you can pin it in the package managers so it doesn't ruin the mods.

I don't know ansible, but most of these seem easy from a os/shell standpoint, so I might can help out....cept the battery one :D
If you want these broken out to seperate issues, let me know

**Comment by rdbell** [comment]
I don't have linux installed on the GPD yet, but some systems will send an event to udev whenever the battery charges/discharges by 1%. Can you try running `udevadm monitor` and see if an event gets fired when your battery % changes?

**Comment by cawilliamson** [comment]
1.) Already fixed - you're not running the latest kernel

2.) I haven't seen this at my end and have been running Arch for weeks.

3.) brcmfmac is absolutely setup at startup and again, has been for weeks.

4.) I don't even know how you would right click on a touchscreen? :O More info?

5.) You make a good point here - I could symlink the latest kernel sources to the correct path. Hmm, good shout.

For issues 1-3 - I haven't had any other reports of this on -rc5, I suspect you're somehow still running the -bootstrap kernel (which shouldn't even be present if you're run `sudo gpd-update` and let the new kernel build and install.

**Comment by snazzybunny** [comment]
step 5 would be helpful :)

**Comment by icebal** [comment]
rerunning gpd-update now, and will past bin it. i have been running it every day for the last 3 days and rebooting afterward and still shows as 4.13.0-rc0-bootstrap.

**Comment by icebal** [comment]
https://hastebin.com/nuporetaxa.sql

shows as 0 changed and 44=ok. 1-3 would explain a lot if some reason its not compiling the kernel correctly. whats the link to his source and see if i can pull it down manually and build it.

**Comment by icebal** [comment]
after reboot, still same kernel. the only vmlinuz and initrd found via grub is the bootstrap. same in the /boot/grub dir, and when grub-mkconfig is ran.

**Comment by cawilliamson** [comment]
Could you provide the output of the following?

```
ls -l /boot/
ls -l /lib/modules/
```

**Comment by icebal** [comment]
ls -l /boot/                            (08-19 04:02)
total 31404
-rwxr-xr-x 1 root root   193627 Aug  4 09:04 config-4.13.0-rc0-bootstrap
drwxr-xr-x 3 root root     4096 Aug 17 21:26 EFI
drwxr-xr-x 6 root root     4096 Aug 19 03:54 grub
-rwxr-xr-x 1 root root 19489322 Aug 18 00:19 initrd.img-4.13.0-rc0-bootstrap
-rwxr-xr-x 1 root root  1303040 Jul  9 07:15 intel-ucode.img
drwxr-xr-x 2 root root     4096 Aug 18 20:10 syslinux
-rwxr-xr-x 1 root root  3675035 Aug  4 09:04 System.map-4.13.0-rc0-bootstrap
-rwxr-xr-x 1 root root  7468816 Aug  4 09:04 vmlinuz-4.13.0-rc0-bootstrap


ls -l /lib/modules/                     (08-19 04:02)
total 8
drwxr-xr-x 3 root root 4096 Aug 18 19:06 4.12.8-1-ARCH
drwxr-xr-x 3 root root 4096 Aug  4 09:04 4.13.0-rc0-bootstrap

**Comment by cawilliamson** [comment]
@icebal Not sure how your system ended up in this state but try the following:

```
sudo -s
rm -rf /usr/src/linux-jwrdegoede
gpd-update
reboot
```

Then let me know if you're still having problems after that. 👍

**Comment by cawilliamson** [comment]
Actually - I've been thinking about point 5 (DKMS) and I don't think you're right here.

I don't rename anything - it's created with those names at boot time on gpd-update. The only times files are renamed are for the iso bootstrap.

In short: DKMS works just fine on a fully installed system (not still running bootstrap kernel.)

With respect - I'm going to close this one because:

1.) I cannot reproduce the issues
2.) I suspect ALL of these issues are stemming from the fact that you're not running an updated kernel. Perhaps this was a bug I introduced previously but it should be resolved at this point.

If you perform the steps above and your issue persists (or you get an error) feel free to re-open (or just update) the ticket at that point.

Thanks!

**Comment by icebal** [comment]
clearing and re-running worked for 1 and 4, which are thebiggest things :D 2 still is happening, but i dont think its an issue with the bootstrap, so thats off the table. 5 is still an issue, but that is only beause default headers are for 4.12.8-1-ARCH and not the 4.13 kernel we are using :) thank you for your help! as for the multitouch touchscreen that windows is able to utilize, i will look into a linux version and get bak to you about it.

**Comment by cawilliamson** [comment]
You know "headers" are basically just the kernel source code, right?

You have the entire kernel source code at /usr/src/linux-*

All you have to do is tell DKMS to look at that path and you can install all the DKMS modules you like. 👍
